### PR TITLE
List licenses

### PR DESCRIPTION
**Pull request by iamleeg**
Hi, I needed a tool to audit the third-party licenses used in a Composer project and the easiest way to get this was to adapt your license-file generator. I hope my additions are useful!

### CODE REVIEW

**Comment by orediggerco** [comment]
Hey @iamleeg, thanks again for this PR. I definitely like the addition and think it could be useful to just show the license name to stdout, in addition to sending the full license texts to a file. 

But with the new command called `ListCommand` it actually takes the place of Symfony's default, built-in,`ListCommand` which prints basic usage information as well as the name of all available commands. Basically it means that we can no longer see the list of all commands in the app with it named this way.

I did some testing locally and verified that by changing the name of the `ListCommand` class, filename, and the `$app->add()` call in `bin/php-legal-licenses` to something like `ShowCommand` (with a name of just `show`), all the commands list correctly in the main help output.

I'd be happy to merge+tag this addition if you could make this change. Thanks!

**Comment by iamleeg** [comment]
🤦‍♂️ thanks, I didn't think about a collision with existing command names.

**Comment by kiler129** [comment]
How is this different from `composer licenses list`?

**Comment by orediggerco** [comment]
@kiler129, not sure if you're referring to this change or the project in general, but there are a few use cases I can think of where this project would be helpful. For example, in some cases the composer phar isn't present in a production environment, and if this package is installed with the application, it can still be run to show license information.

I also have had some other ideas to extend it, that as far as I know composer does not support, like configurable warnings for certain types of licenses that may not be allowed for one reason or another.

**Pull request merged**
